### ISSUE TITLE
Separation of configuration values and logic

### ISSUE THREAD

**Issue by nikoheikkila** [pelilegacy/DynamicLayout#3]
It is a good practice to separate the data from the logic even in smaller applications. Hardcoding the configuration values into scripts is usually a very bad thing. [Here](http://programmers.stackexchange.com/a/68219) are some good reasons why.

So, instead of doing this:

```javascript
var channel = "pelilegacy_fi";
```

Do something like this (example file could be named _config.json_):

```json
{
    "urls": {
        "twitch": "http://twitch.tv/channel",
        "hitbox": "http://hitbox.tv/channel",
        "alert": "http://example.com/twitchalert"
    },
    "players": { ... }
}
```

Then query the data inside the Javascript file with eg. `$.getJSON()`.

**Comment by Arkkis** [comment]
Done with https://github.com/pelilegacy/DynamicLayout/commit/c741230ade3da0fd2bd2683cc7cf3f7c81069a57 ?

**Comment by nikoheikkila** [comment]
Good for now, @Arkkis. Closing this.
